## This is a simplified action for building and testing a Bioconductor package
## based on https://github.com/lcolladotor/biocthis/blob/master/actions/check-bioc.yml
## and https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml

name: R-CMD-check-bioc

## Specify which branches to run on
## The "master" branch corresponds to Bioc-devel and "RELEASE_X" branches are
## Bioconductor releases. See http://bioconductor.org/developers/how-to/git/.
on:
  push:
    branches:
      - master
      - 'RELEASE_*'
  pull_request:
    branches:
      - master
      - 'RELEASE_*'

jobs:
  ## Use the GitHub repository branch name to find the Bioconductor version
  get-bioc-release:
    runs-on: ubuntu-latest
    outputs:
      biocimage: ${{ steps.info.outputs.biocimage }}
      biocversion: ${{ steps.info.outputs.biocrelease }}
    steps:
      - id: info
        run: |
          if echo "$GITHUB_REF" | grep -q "RELEASE_"; then
              biocrelease="$(basename -- $GITHUB_REF | tr '[:upper:]' '[:lower:]')"
          else
              biocrelease="devel"
          fi
          biocimage="bioconductor/bioconductor_docker:${biocrelease}"
          echo "Bioc release: ${biocrelease}"
          echo "Bioc docker image: {$biocimage}"
          ## Store the information
          echo "::set-output name=biocimage::${biocimage}"
          echo "::set-output name=biocrelease::${biocrelease}"

  get-bioc-version:
    runs-on: ubuntu-latest
    needs: get-bioc-info
    image: ${{ needs.get-bioc-release.outputs.biocimage }}
    outputs:
      Rversion: ${{ steps.info.set-versions.rversion }}
      biocversion: ${{ steps.info.set-versions.rversion }}
    steps
      - id: get-versions
        run: |
          biocconfig <- "https://bioconductor.org/config.yaml"
          biocrelease <- ifelse(
            grepl("${{ needs.get-bioc-release.outputs.biocrelease }}", "release"),
            "release", "devel")
          biocmap <- BiocManager:::.version_map_get_online(biocconfig)
          biocversion <- subset(biocmap, BiocStatus == biocrelease)[, 'Bioc']
          rversion <- subset(biocmap, BiocStatus == biocrelease)[, 'R']
          writeLines(as.character(c(biocversion, rversion)),
                     ".github/versions.txt")
          cat("SET VERSIONS")
          cat("Bioc release: ", biocrelease)
          cat("Bioc version: ", biocversion)
          cat("R version: ", rversion)
        shell: Rscript {0}
      - id: set-versions
        run: |
          biocversion=$(head -n 1 github/versions.txt)
          rversion=$(tail -n 1 github/versions.txt)
          echo "GET VERSIONS"
          echo "Bioc version: {$biocversion}"
          echo "R version: {$rversion}"
          ## Store the information
          echo "::set-output name=biocversion::${biocversion}"
          echo "::set-output name=rversion::${rversion}"
